apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataserver-deployment
  labels:
    app: data-server
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: data-app
          image: avivhagever/data-serverimage
          ports:
           —containerPort: 80