---
kind: Service
apiVersion: v1
metadata:
  name: data-service
  labels:
    app: data-server
spec:
  type: NodePort
  selector:
    app: data-server
  ports:
    - name: data-server
      port: 8000
      nodePort: 30990
      targetPort: 8000
