name: Deploy

on:
    push:
        branches: [main]
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: azure/setup-kubectl@v3
            - uses: azure/k8s-set-context@v3
              with:
                  method: kubeconfig
                  kubeconfig: ${{ secrets.KUBECONFIG }}
            - uses: actions/checkout@v3
            - run: |
                kubectl apply -f deployment.yaml -n data || true
                kubectl apply -f service.yaml -n data || true
